services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./docs:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling --source ./docs
