title: Alex Kozlov
description: Personal website and blog
baseurl: ""
url: "https://aramakus.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# GitHub Pages settings
repository: aramakus/alexkozlov.github.io

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
