title: Personal Website and Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website and blog hosted on GitHub Pages.
url: "https://aramakus.github.io"
baseurl: ""

# Build settings
markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
